### PR TITLE
File rework for ebook publishing

### PR DESCRIPTION
**Pull request by jnavila**
Hi all,

I'm in the process of making an automatic publication of the book on git-scm.com, using asciidoctor and Travis-CI. This PR reorganizes the files so that the resulting epub and PDFs are correct.

 * I add to split the preface into sub-chapters
 * I added the table of contents (automatic translation of the title in `progit.asc`)
 * I added the licence info (automatic translation)

Please review the changes. The automatic build should already be active.

If everything is ok, I'll add the publishing step.

### CODE REVIEW

**Comment by networm** [comment]
Thank you for your excellent work!

**Comment by networm** [comment]
There is an error when travis-ci build:

> The command "wget https://raw.githubusercontent.com/progit/progit2-pub/master/bootstrap.sh" failed and exited with 8 during .

Need we update some config?

**Comment by jnavila** [comment]
No, sorry. I had forgotten to push the latest version on the build tools repository.

**Comment by networm** [comment]
Just push and I will merge it immediately.

**Comment by jnavila** [comment]
I pushed on the build tools repo. It is working now.

**Comment by jnavila** [comment]
https://travis-ci.org/progit/progit2-zh/builds/343290028

**Comment by networm** [comment]
OK, I see it. Build is successful.

**Comment by networm** [comment]
Where could we download built pdf and epub files?

**Comment by jnavila** [comment]
I'm working on it ;-)

**Comment by networm** [comment]
OK, could you reply this conversation after you have done?

**Comment by networm** [comment]
Or where could I subscribe it?

**Comment by jnavila** [comment]
They will be shortly available at https://github.com/progit/progit2-zh/releases

After a day or so, the link will be available on https://git-scm.com/book/zh

**Comment by jnavila** [comment]
Done!

**Comment by networm** [comment]
Is these work done manually? It seems too long for about one day to take effect on main site.

**Comment by jnavila** [comment]
No, it's a cron job.

**Comment by networm** [comment]
It seems that an indentation bug still exist in Chinese pdf. So I think the first thing should do is syncing with English repository. Progit-zh is about two years behind progit.
If I have any questions about generating pdf, who should I ask for help?

**Comment by jnavila** [comment]
Don't hesitate to ask. There may be bugs in asciidoctor too, specially for CJK languages.

**Comment by networm** [comment]
Thank you for your help!

**Comment by jnavila** [comment]
I guess that this is due to the algorithm for composing the lines of text that tries to do it in "justify" mode, and only uses the space characters (whitespace, carriage return) to break the lines of text. As most asian languages mostly don't use space between words, the dumb algorithm breaks the lines at the very seldom spaces it encounters and doesn't know how to average the spacing between characters.

I don't really know what we can do from that now. There's an extension https://github.com/chloerei/asciidoctor-pdf-cjk that seems to address this, but I can't make it work. Or we can try to force left align of text (but this option will still split lines randomly).

**Comment by jnavila** [comment]
I applied the changes from @chloerei and it seems to be working correctly.

**Comment by networm** [comment]
I have compared 2.1.4 and 2.1.1, they have minor difference that line width is shorter in 2.1.4. And it seems very good in layout. So I think you needn't to do anything else.

**Comment by YueLinHo** [comment]
cc/ @taichunmin

**Comment by jnavila** [comment]
Please note that the index is not translated. I'm not sure asciidoctor handles correctly Chinese for asciidoctor.

**Comment by networm** [comment]
I have checked asciidoctor documentation. The problem is that we didn't set appendix caption and untranslated Index word.
I have pushed two commits to fix these problems.
https://github.com/progit/progit2-zh/commit/5ed7dda9b3b9f94127ccd53969adaeaa14b1299d

**Comment by networm** [comment]
61. Appendix - Asciidoctor User Manual
http://asciidoctor.org/docs/user-manual/#user-appendix

64.2. Index Catalog - Asciidoctor User Manual
http://asciidoctor.org/docs/user-manual/#index-catalog

**Comment by networm** [comment]
Could you add project name and version to output files? Like `progit-zh-v2.1.5.pdf` `progit-zh-v2.1.5.epub` and so on. I think different langauge should have different prefix and version to identifiy.

**Comment by networm** [comment]
I have also checked the v2.1.5 pdf, `Appendix` and `Index` has been translated to Chinese.

**Comment by jnavila** [comment]
There are two sides of this request:
 * Should we include the version in the generated content? I think so. We could use the document extensions to do so. See https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#document-header
 * Changing the file names is a bit trickier. Travis deployment description is static but it allows to use environment variables. But there's nothing stating at which point the environment variables are replaced in the file. That would need some tests.

I've open a new issue progit/progit2-sub#1 to track this feature.

**Comment by networm** [comment]
I think you could just use `repo = ENV['TRAVIS_REPO_SLUG']` to get repository name and substring to get project name.

**Comment by jnavila** [comment]
@networm I included the version in the file name and in the generated content.

What you are proposing now is to add the language too?

**Comment by networm** [comment]
Yes, I mean we could use `progit2-zh` in `progit/progit2-zh` as file name prefix.

**Comment by jnavila** [comment]
That could work with your repository, but there are others that don't follow the same naming scheme and doing a generic processing on the repo name would be more difficult.

**Comment by networm** [comment]
It is OK without repository name. And I have another question. It seems that every push will trigger one build, but why it automatically created a tag to release page. Could we create a tag to release page manually?

**Comment by jnavila** [comment]
That's part of the automatic deployment. If a build on a new commit on master succeeds, it is automatically tagged (I use a private API token for this). Then, the build is relaunched and the artifacts deployed at the release on GitHub, where they are available for download from git-scm.com.

As every "good" commit to master will be tagged and turn into a release, you don't need to manually create a tag. Why would you want to create a tag manually?

**Comment by networm** [comment]
I want to add release notes in every release. Could you collect all commit message as release notes?

**Pull request merged**
