### PR TITLE
Escaping quotation marks within an attribute block

### PR DESCRIPTION
**Pull request by sandersk**
Hi @networm,

I've escaped the quotation marks in the attribute block for this `image::` markup:

````
image::images/vs-2.png[Visual Studio 中的 Git 仓库的 "Home" 视图。]
````

Which should correct the build error for the book.

Hope this helps,
Sanders

### CODE REVIEW

**Comment by networm** [comment]
@sandersk Sorry, we need to change quotation mark to full width. So I created another PR to fix this.

**Comment by networm** [comment]
@sandersk Thank you very much! We have passed building! [Pro Git build progress](https://progit.org/translations/lang/zh)

**Comment by oldsharp** [comment]
We could have cherry-picked 77b8812 , then either amend it or add a new commit on top of it.
If we had done that, then #243 might not have to be opened.

**Comment by networm** [comment]
@sandersk We have merged your Pull Request.
@oldsharp I have merged it.

**Pull request merged**
